repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-merge-conflict

-   repo: local
    hooks:
    -   id: commitlint
        name: Commitlint
        entry: npx --no -- commitlint --edit
        language: node
        pass_filenames: false
        stages: [commit-msg]
        verbose: true

    -   id: local-biome-check
        name: biome check
        entry: pnpx @biomejs/biome check --write --files-ignore-unknown=true --no-errors-on-unmatched
        language: node
        types: [text]
        files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?)$"
