repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # 更新到最新版本
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict  # 检查合并冲突
    -   id: check-json  # 检查JSON文件格式

-   repo: local
    hooks:
    -   id: commitlint
        name: Commitlint
        entry: npx --no -- commitlint --edit
        language: node
        pass_filenames: false
        stages: [commit-msg]
        verbose: true

    -   id: lint-staged
        name: Lint Staged Files
        entry: npx lint-staged
        language: node
        pass_filenames: false
        stages: [commit]
